const initialState = {
  selfInf: {
    name: 'Kat Williams',
    link: '@Williams',
    podilePhoto: require('../src/assets/img/ProfileImage.png'),
    country: 'Россия',
    city: 'Санкт-Петербург',
    birthDay: '08 октября 1992',
    status: 'They never ask people to do things they wouldn’t do themselves.',
    workpalce: 'Artist by Passion!',
    studies: 'ВГУЮ в г. Санкт-Петербург',
  },
  social: {
    arrow: 'http://t.me/durov',
    twitter: 'Durov',
    instagram: 'Pavel Durov',
    facebook: 'durov',
    telegram: 'durov',
  },
  followers: '2467',
  following: '1589',
  friends: [
    {
      id: '1',
      name: 'Kat Williams',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '2',
      name: 'Monegros Acid Resort',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '3',
      name: 'Kat Williams',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '4',
      name: 'Kat Williams',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '5',
      name: 'Monegros Acid Resort',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '6',
      name: 'Ruck',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '11',
      name: 'Kat Williams',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '21',
      name: 'Monegros Acid Resort',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '31',
      name: 'Kat Williams',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '41',
      name: 'Kat Williams',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '51',
      name: 'Monegros Acid Resort',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '61',
      name: 'Ruck',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '13',
      name: 'Kat Williams',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '23',
      name: 'Monegros Acid Resort',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '33',
      name: 'Kat Williams',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '43',
      name: 'Kat Williams',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '53',
      name: 'Monegros Acid Resort',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
    {
      id: '63',
      name: 'Ruck',
      profilePhoto: require('../src/assets/img/ProfileImage.png'),
      city: 'Санкт-Петербург',
    },
  ],
  postInformation: [
    {
      postID: '1',
      postHolder: 'Kat Williams',
      holderPhoto: require('../src/assets/img/postPhotoProfile/p1.png'),
      postDate: '1h ago',
      like: '8998',
      postText: 'Writing code is not so bad!',
      postPhoto: require('../src/assets/img/postPhoto/1.png'),
      commentList: [
        {
          commetHolder: 'Kat Williams',
          body: 'User experience design for the Web (and its siblings, interaction design, UI design, et al) has traditionally been a deliverables-based practice.',
          image: null,
          date: '25 сен. в 22:12 ',
          id: '5a01231d-3ee9-4bf6-9a12450-462a8277898a',
          like: '12',
          parent: null,
          reply: [
            {
              commetHolder: 'Kat Williams',
              body: 'User experience design for the Web (and its siblings.',
              image: null,
              date: '25 сен. в 22:12 ',
              id: '514aa634-08bd-4ca3-8a1a-eb10846808ed',
              parent: '5a0123114244d-3ee9-4bf6-9a50-462a8277898a',
              like: '12',
              reply: [],
            },
            {
              commetHolder: 'Kat Williams',
              body: 'User experience design for the Web (and its siblings.',
              image: null,
              date: '25 сен. в 22:12 ',
              id: '514aa634-08bd-s4ca3-8a1a-eb1012846808ed',
              parent: '5a01231d-3ee9-4bf6-9a50-462a827784498a',
              like: '12',
              reply: [],
            },
          ],
        },
        {
          commetHolder: 'Kat Williams',
          body: null,
          image: require('../src/assets/img/CommentPhoto.png'),
          date: '25 сен. в 22:12 ',
          id: '01793ef41-fdb6-4700-a4dc-6d7bbc54385a',
          like: '12',
          parent: null,
          reply: [],
        },
        {
          commetHolder: 'Kat Williams',
          body: 'User experience design for the Web (and its siblings, interaction design, UI design, et al) has traditionally been a deliverables-based practice.',
          image: null,
          date: '25 сен. в 22:12 ',
          id: '1ef06878-58b5-48b0-9349-73986ab616bb4',
          like: '12',
          parent: null,
          reply: [],
        },
        {
          commetHolder: 'Kat Williams',
          body: 'User experience design for the Web (and its siblings, interaction design, UI design, et al) has traditionally been a deliverables-based practice.',
          image: require('../src/assets/img/CommentPhoto.png'),
          date: '25 сен. в 22:12 ',
          id: '1ef06878-58b5-481b0-9349-73986ab66bb4',
          like: '12',
          parent: null,
          reply: [],
        },
      ],
    },
    {
      postID: '2',
      postHolder: ' Tony Monta',
      holderPhoto: require('../src/assets/img/postPhotoProfile/p2.png'),
      postDate: '1h ago',
      like: '14',
      postText: 'Writing code is not so bad!',
      postPhoto: null,
      commentList: null,
    },
    {
      postID: '3',
      postHolder: ' Jessica Thompson',
      holderPhoto: require('../src/assets/img/postPhotoProfile/p3.png'),
      postDate: '2h ago',
      like: '17',
      postText: null,
      postPhoto: require('../src/assets/img/postPhoto/2.png'),
      commentList: null,
    },
    {
      postID: '4',
      postHolder: 'Dustin Grant',
      holderPhoto: require('../src/assets/img/postPhotoProfile/p4.png'),
      postDate: '3h ago',
      like: '238',
      postText: null,
      postPhoto: require('../src/assets/img/postPhoto/3.png'),
      commentList: null,
    },
  ],
  gallary: [
    {
      id: '1',
      title: 'First Item',
      source: require('../src/assets/img/profilePhotoScrol/1.png'),
    },
    {
      id: '2',
      title: 'First Item',
      source: require('../src/assets/img/profilePhotoScrol/2.png'),
    },
    {
      id: '3',
      title: 'First Item',
      source: require('../src/assets/img/profilePhotoScrol/3.png'),
    },
    {
      id: '4',
      title: 'First Item',
      source: require('../src/assets/img/profilePhotoScrol/4.png'),
    },
    {
      id: '5',
      title: 'First Item',
      source: require('../src/assets/img/profilePhotoScrol/5.png'),
    },
    {
      id: '6',
      title: 'First Item',
      source: require('../src/assets/img/profilePhotoScrol/6.png'),
    },
    {
      id: '7',
      title: 'First Item',
      source: require('../src/assets/img/profilePhotoScrol/7.png'),
    },
    {
      id: '8',
      title: 'First Item',
      source: require('../src/assets/img/profilePhotoScrol/8.png'),
    },
    {
      id: '9',
      title: 'First Item',
      source: require('../src/assets/img/profilePhotoScrol/9.png'),
    },
    {
      id: '13',
      title: 'First Item',
      source: require('../src/assets/img/profilePhotoScrol/1.png'),
    },
    {
      id: '14',
      title: 'First Item',
      source: require('../src/assets/img/profilePhotoScrol/2.png'),
    },
    {
      id: '15',
      title: 'First Item',
      source: require('../src/assets/img/profilePhotoScrol/3.png'),
    },
  ],
};

export default initialState;
